# Generated by Django 4.2.17 on 2025-03-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('content', models.TextField(verbose_name='检测文本')),
                ('sentiment', models.CharField(max_length=50, verbose_name='情感分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件上传检测结果',
                'verbose_name_plural': '文件上传检测结果',
            },
        ),
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('pred_name', models.CharField(max_length=100, verbose_name='预测结果')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
            ],
            options={
                'verbose_name': '文本检测',
                'verbose_name_plural': '文本检测',
                'db_table': 'db_check',
            },
        ),
        migrations.CreateModel(
            name='FileEmotionAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('main_emotion', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextEmotionAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('main_emotion', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
